# Generated by Django 3.1.4 on 2021-04-03 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
